/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BagRouteImport } from './routes/bag'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminAnalyticsRouteImport } from './routes/admin_.analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin_.categories'
import { Route as AdminDisputesRouteImport } from './routes/admin_.disputes'
import { Route as AdminModerationRouteImport } from './routes/admin_.moderation'
import { Route as AdminProductsRouteImport } from './routes/admin_.products'
import { Route as AdminReportsRouteImport } from './routes/admin_.reports'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as EditListingIdRouteImport } from './routes/edit-listing.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as SellerUsernameRouteImport } from './routes/seller.$username'
import { Route as SwapsIdRouteImport } from './routes/swaps.$id'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as WalletReceiptIdRouteImport } from './routes/wallet/receipt/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin_/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin_/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin_/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin_/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin_/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const EditListingIdRoute = EditListingIdRouteImport.update({
  id: '/edit-listing/$id',
  path: '/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerUsernameRoute = SellerUsernameRouteImport.update({
  id: '/seller/$username',
  path: '/seller/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapsIdRoute = SwapsIdRouteImport.update({
  id: '/swaps/$id',
  path: '/swaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletReceiptIdRoute = WalletReceiptIdRouteImport.update({
  id: '/wallet/receipt/$id',
  path: '/wallet/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bag': typeof BagRoute
  '/browse': typeof BrowseRoute
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/swaps/$id': typeof SwapsIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/receipt/$id': typeof WalletReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bag': typeof BagRoute
  '/browse': typeof BrowseRoute
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/swaps/$id': typeof SwapsIdRoute
  '/messages': typeof MessagesIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/wallet/receipt/$id': typeof WalletReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bag': typeof BagRoute
  '/browse': typeof BrowseRoute
  '/check-email': typeof CheckEmailRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin_/analytics': typeof AdminAnalyticsRoute
  '/admin_/categories': typeof AdminCategoriesRoute
  '/admin_/disputes': typeof AdminDisputesRoute
  '/admin_/moderation': typeof AdminModerationRoute
  '/admin_/products': typeof AdminProductsRoute
  '/admin_/reports': typeof AdminReportsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/edit-listing/$id': typeof EditListingIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/seller/$username': typeof SellerUsernameRoute
  '/swaps/$id': typeof SwapsIdRoute
  '/messages/': typeof MessagesIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/wallet/receipt/$id': typeof WalletReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bag'
    | '/browse'
    | '/check-email'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/saved-searches'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/users'
    | '/edit-listing/$id'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/swaps/$id'
    | '/messages/'
    | '/wallet/'
    | '/wallet/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bag'
    | '/browse'
    | '/check-email'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/saved-searches'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/users'
    | '/edit-listing/$id'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/swaps/$id'
    | '/messages'
    | '/wallet'
    | '/wallet/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bag'
    | '/browse'
    | '/check-email'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/saved-searches'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin_/analytics'
    | '/admin_/categories'
    | '/admin_/disputes'
    | '/admin_/moderation'
    | '/admin_/products'
    | '/admin_/reports'
    | '/admin_/users'
    | '/edit-listing/$id'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/seller/$username'
    | '/swaps/$id'
    | '/messages/'
    | '/wallet/'
    | '/wallet/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BagRoute: typeof BagRoute
  BrowseRoute: typeof BrowseRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EditListingIdRoute: typeof EditListingIdRoute
  ListingIdRoute: typeof ListingIdRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  SellerUsernameRoute: typeof SellerUsernameRoute
  SwapsIdRoute: typeof SwapsIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  WalletReceiptIdRoute: typeof WalletReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/analytics': {
      id: '/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/categories': {
      id: '/admin_/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/disputes': {
      id: '/admin_/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/moderation': {
      id: '/admin_/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/products': {
      id: '/admin_/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reports': {
      id: '/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-listing/$id': {
      id: '/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof EditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$username': {
      id: '/seller/$username'
      path: '/seller/$username'
      fullPath: '/seller/$username'
      preLoaderRoute: typeof SellerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swaps/$id': {
      id: '/swaps/$id'
      path: '/swaps/$id'
      fullPath: '/swaps/$id'
      preLoaderRoute: typeof SwapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/receipt/$id': {
      id: '/wallet/receipt/$id'
      path: '/wallet/receipt/$id'
      fullPath: '/wallet/receipt/$id'
      preLoaderRoute: typeof WalletReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BagRoute: BagRoute,
  BrowseRoute: BrowseRoute,
  CheckEmailRoute: CheckEmailRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  EditListingIdRoute: EditListingIdRoute,
  ListingIdRoute: ListingIdRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  SellerUsernameRoute: SellerUsernameRoute,
  SwapsIdRoute: SwapsIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  WalletReceiptIdRoute: WalletReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
